### ISSUE TITLE
Reduce npm package

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-pre-commit#10]
The small npm package size is one of the key features of this package. There is a reason to use every micro-optimization for art reasons.

For instance, adding and calling [clean-publish](https://github.com/shashkovdanil/clean-publish)  instead of `npm publish` will remove `devDependencies`, `lint-staged`, etc from `package.json`.

**Comment by toplenboren** [comment]
Thanks! With `clean-publish` I was able to go from `12 kB` to `10.9 kB` But I feel it's not the limit. 

Wanna try minifying the code to see If i can stay below `10.0 kB`.

**Comment by toplenboren** [comment]
I was able to go below `10.0 kB` by removing docstrings and other non relevant stuff from sources in npm. Think the next stage is automating the process with github actions

Gonna close the issue for now, Thanks!
