### ISSUE TITLE
Stand-alone config name

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-pre-commit#15]
I found that `.simple-pre-commit.json` (with dot) doesn’t work in the latest version.

```sh
➜ cat .simple-pre-commit.json 
{
  "simple-pre-commit": "npx lint-staged"
}

➜ npx simple-pre-commit      
Couldn't parse command! Please add command to package.json or .simple-pre-commit.json. See README.md for details
os.exit is not a function

➜ mv .simple-pre-commit.json simple-pre-commit.json  

➜ npx simple-pre-commit                            
Set pre commit hook: npx lint-staged
```

I personally prefer configs with `.`, but it is not a big deal. We can just change docs to promote only `simple-pre-commit.json`.

**Comment by toplenboren** [comment]
Whoa, gonna look through it, Thanks

**Comment by toplenboren** [comment]
Added an ablitiy to set either `.simple-pre-commit.json` or `simple-pre-commit.json` or `simple-pre-commit` key in `package.json`
