### ISSUE TITLE
Linux support regression: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-pre-commit#18]
`npx simple-pre-commit` now returns an error on Linux systems:

```
/usr/bin/env: ‘node\r’: No such file or directory
```

Seems like the script has Windows `\r\n` symbols. Maybe we need to change some git settings.

**Comment by toplenboren** [comment]
Gonna look into this issue, thanks!

**Comment by toplenboren** [comment]
Yep, the problem was with windows delimeters. Should be fixed by now, but I haven't been able to widely test it.

Gonna leave the issue open for now

**Comment by toplenboren** [comment]
Tested latest version on linux, it seems, like the bug was fixed
