### ISSUE TITLE
Add `uninstall` script

### ISSUE THREAD

**Issue by ai** [toplenboren/simple-pre-commit#4]
We have `postinstall` to set `.git/hooks/pre-commit`, but we forgot about the `uninstall` script to remove the script on the `simple-pre-commit` unsinatlling

**Comment by ai** [comment]
It will be nice to have similar output explaining what happened during uninstall:

```
➜ yarn remove husky
yarn remove v1.22.10
warning package.json: No license field
[1/2] Removing module husky...
$ node husky uninstall
husky > Uninstalling git hooks
husky > Done
$ node husky uninstall
husky > Uninstalling git hooks
husky > Done

~
```

**Comment by toplenboren** [comment]
Added an `uninstall script` in 1.2.* release, Thanks!
